# Generated by Django 5.0.1 on 2024-02-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0002_rename_close_price_stockdata_close_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='close',
            new_name='close_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='open',
            new_name='open_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='ticker',
            new_name='ticker_symbol',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low',
        ),
    ]
